name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Cancel previous runs for the same PR/branch
defaults:
  run:
    shell: bash

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          check-latest: true

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint with ESLint
        run: npx eslint . --max-warnings=0

      - name: Run tests
        run: npm test

      - name: Generate documentation
        run: npm run docs

      - name: Upload coverage report
        if: success() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage/
            docs/
          retention-days: 7
          path: htmlcov/